/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'font-myriad-pro',
    'font-bitter',
    'text-h1-mobile',
    'text-h2-mobile',
    'text-h3-mobile', 
    'text-h4-mobile',
    'text-h1-desktop',
    'text-h2-desktop',
    'text-h3-desktop',
    'text-h3-desktop-uppercase',
    'text-h4-desktop',
    'text-h4-desktop-uppercase',
    'text-p',
    'text-p-mobile',
    'text-p-introduction',
    'text-p-introduction-mobile',
    'text-p-uppercase',
    'text-p-uppercase-mobile',
    'text-p-bold',
    'text-p-bold-mobile',
    'text-p-bold-uppercase',
    'text-p-bold-uppercase-mobile',
    'text-p-italic',
    'text-p-italic-mobile',
    'text-p-small',
    'text-p-small-uppercase-bold',
    'text-p-small-uppercase-mobile',
    'text-button',
    'text-button-mobile',
    'text-menu',
    'uppercase'
  ],
  theme: {
    extend: {
      fontFamily: {
        'myriad-pro': ['var(--font-myriad-pro)'],
        'bitter': ['var(--font-bitter)'],
        sans: ['var(--font-myriad-pro)'],
        mono: ['var(--font-geist-mono)'],
      },
      fontSize: {
        // Desktop typography
        'h1-desktop': ['72px', { lineHeight: '72px', fontWeight: '700', letterSpacing: '0', textTransform: 'uppercase' }],
        'h2-desktop': ['36px', { lineHeight: '44px', fontWeight: '500', letterSpacing: '1.08px' }],
        'h3-desktop': ['30px', { lineHeight: '40px', fontWeight: '500', letterSpacing: '0' }],
        'h3-desktop-uppercase': ['30px', { lineHeight: '40px', fontWeight: '500', letterSpacing: '3px', textTransform: 'uppercase' }],
        'h4-desktop': ['24px', { lineHeight: '32px', fontWeight: '500', letterSpacing: '0.48px' }],
        'h4-desktop-uppercase': ['24px', { lineHeight: '28.8px', fontWeight: '700', letterSpacing: '0', textTransform: 'uppercase' }],
        'p-introduction': ['36px', { lineHeight: '48px', fontWeight: '400', letterSpacing: '0' }],
        'p': ['16px', { lineHeight: '24px', fontWeight: '400', letterSpacing: '0' }],
        'p-uppercase': ['16px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '1.12px', textTransform: 'uppercase' }],
        'p-bold': ['16px', { lineHeight: '24px', fontWeight: '700', letterSpacing: '0' }],
        'p-bold-uppercase': ['16px', { lineHeight: '20px', fontWeight: '700', letterSpacing: '1.12px', textTransform: 'uppercase' }],
        'p-italic': ['16px', { lineHeight: '24px', fontWeight: '400', letterSpacing: '0', fontStyle: 'italic' }],
        'p-small': ['14px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '0.84px', textTransform: 'uppercase' }],
        'p-small-uppercase-bold': ['14px', { lineHeight: '16.8px', fontWeight: '700', letterSpacing: '0.7px', textTransform: 'uppercase' }],
        'button': ['16px', { lineHeight: '18px', fontWeight: '600', letterSpacing: '0' }],
        'menu': ['18px', { lineHeight: '18px', fontWeight: '400', letterSpacing: '0' }],
        
        // Mobile typography
        'h1-mobile': ['28px', { lineHeight: '28px', fontWeight: '700', letterSpacing: '0', textTransform: 'uppercase' }],
        'h2-mobile': ['24px', { lineHeight: '28.8px', fontWeight: '500', letterSpacing: '0' }],
        'h3-mobile': ['20px', { lineHeight: '24px', fontWeight: '500', letterSpacing: '0' }],
        'h4-mobile': ['18px', { lineHeight: '21.6px', fontWeight: '500', letterSpacing: '0' }],
        'p-introduction-mobile': ['16px', { lineHeight: '19.2px', fontWeight: '400', letterSpacing: '0' }],
        'p-mobile': ['14px', { lineHeight: '18px', fontWeight: '400', letterSpacing: '0' }],
        'p-uppercase-mobile': ['14px', { lineHeight: '16.8px', fontWeight: '400', letterSpacing: '0.98px', textTransform: 'uppercase' }],
        'p-bold-mobile': ['14px', { lineHeight: '16.8px', fontWeight: '700', letterSpacing: '0' }],
        'p-italic-mobile': ['14px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '0', fontStyle: 'italic' }],
        'button-mobile': ['14px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0' }],
        'p-small-uppercase-mobile': ['12px', { lineHeight: '14.4px', fontWeight: '400', letterSpacing: '0.84px', textTransform: 'uppercase' }],
      },
      colors: {
        border: "rgb(var(--border))",
        input: "rgb(var(--input))",
        ring: "rgb(var(--ring))",
        background: "rgb(var(--background))",
        foreground: "rgb(var(--foreground))",
        primary: {
          DEFAULT: "rgb(var(--primary))",
          foreground: "rgb(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary))",
          foreground: "rgb(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive))",
          foreground: "rgb(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "rgb(var(--muted))",
          foreground: "rgb(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "rgb(var(--accent))",
          foreground: "rgb(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "rgb(var(--popover))",
          foreground: "rgb(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "rgb(var(--card))",
          foreground: "rgb(var(--card-foreground))",
        },
      },
    },
  },
  plugins: [],
}