import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myriadPro = localFont({
  variable: "--font-myriad-pro",
  src: [
    {
      path: "../public/fonts/MyriadPro-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MyriadPro-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/MyriadPro-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/MyriadPro-BoldIt.woff",
      weight: "400",
      style: "italic",
    },
  ],
});

const bitter = localFont({
  variable: "--font-bitter",
  src: [
    {
      path: "../public/fonts/Bitter-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Bitter-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${myriadPro.variable} ${bitter.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
